### PR TITLE
adds strongbox encryption to env files

### PR DESCRIPTION
**Pull request by slawo**

### CODE REVIEW

**Comment by denisnikulin** [comment]
I might have got it wrong, but my understanding is as follows:

1. environment (.env) goes into wiring.yml where env variables should be defined for local/remote development and deployment, and should _NOT_ be encrypted
 *  (in case of .env, there should be .env.dist, not .env deployed?..)
2. `secrets` are the ones to be encrypted and should go into secrets/ folder for consistency.

**Comment by michael-donat** [comment]
@denisnikulin you did get it wrong slightly

wiring.yml has all the params, .env files provide ENV variables, both are different concerns.

we should have secrets.env which is encrypted

you are right that other .env files should not be

we shouldn't have .env.dist anymore

**Comment by michael-donat** [comment]
@denisnikulin putting everything in secrets may be a sensible way out too, this way it's not limited to .env files

**Comment by slawo** [comment]
you'd like to change the scope of the strongbox encryption to `secrets/**`?

**Comment by denisnikulin** [comment]
oops

**Pull request merged**
